import { Injectable, computed, signal } from '@angular/core';

import { Product, ProductCategory } from '../models/product.model';

type PhotoCategory =
  | 'laptops'
  | 'monitors'
  | 'headphones'
  | 'keyboards'
  | 'mice'
  | 'smartwatches'
  | 'speakers'
  | 'webcams'
  | 'desk-accessories'
  | 'charging-accessories';

const photoBase = 'https://images.unsplash.com';

const categoryPhotoSets: Record<PhotoCategory, readonly string[]> = {
  laptops: [
    'photo-1517336714731-489689fd1ca8',
    'photo-1496181133206-80ce9b88a853',
    'photo-1484788984921-03950022c9ef',
    'photo-1541807084-5c52b6b3adef',
  ],
  monitors: [
    'photo-1527443224154-c4a3942d3acf',
    'photo-1593640408182-31c70c8268f5',
    'photo-1527443224154-c4a3942d3acf',
  ],
  headphones: [
    'photo-1505740420928-5e560c06d30e',
    'photo-1546435770-a3e426bf472b',
    'photo-1606220588913-b3aacb4d2f46',
    'photo-1590658268037-6bf12165a8df',
  ],
  keyboards: ['photo-1587829741301-dc798b83add3', 'photo-1618384887929-16ec33fab9ef'],
  mice: ['photo-1527864550417-7fd91fc51a46', 'photo-1615663245857-ac93bb7c39e7'],
  smartwatches: ['photo-1523275335684-37898b6baf30', 'photo-1508685096489-7aacd43bd3b1'],
  speakers: ['photo-1545454675-3531b543be5d', 'photo-1608043152269-423dbba4e7e1'],
  webcams: ['photo-1611162617474-5b21e879e113', 'photo-1590602847861-f357a9332bbc'],
  'desk-accessories': ['photo-1518455027359-f3f8164ba6bd', 'photo-1497366754035-f200968a6e72'],
  'charging-accessories': ['photo-1583863788434-e58a36330cf0', 'photo-1601524909162-ae8725290836'],
};

const productPhotoIds: Record<string, string> = {
  'p-001': 'photo-1517336714731-489689fd1ca8',
  'p-002': 'photo-1496181133206-80ce9b88a853',
  'p-003': 'photo-1527443224154-c4a3942d3acf',
  'p-004': 'photo-1593640408182-31c70c8268f5',
  'p-005': 'photo-1505740420928-5e560c06d30e',
  'p-006': 'photo-1606220588913-b3aacb4d2f46',
  'p-007': 'photo-1587829741301-dc798b83add3',
  'p-008': 'photo-1618384887929-16ec33fab9ef',
  'p-009': 'photo-1527864550417-7fd91fc51a46',
  'p-010': 'photo-1615663245857-ac93bb7c39e7',
  'p-011': 'photo-1523275335684-37898b6baf30',
  'p-012': 'photo-1508685096489-7aacd43bd3b1',
  'p-013': 'photo-1545454675-3531b543be5d',
  'p-014': 'photo-1608043152269-423dbba4e7e1',
  'p-015': 'photo-1611162617474-5b21e879e113',
  'p-016': 'photo-1590602847861-f357a9332bbc',
  'p-017': 'photo-1518455027359-f3f8164ba6bd',
  'p-018': 'photo-1497366754035-f200968a6e72',
  'p-019': 'photo-1583863788434-e58a36330cf0',
  'p-020': 'photo-1601524909162-ae8725290836',
  'p-021': 'eTbVgB8uRgc',
  'p-022': 'YrQ6QXwab6Q',
  'p-023': 'ua0dvtOVr6Q',
  'p-024': 'ClWWV8qMJXk',
  'p-025': 'QpTZcTlk08g',
  'p-026': 'cHlK4sZXOQo',
  'p-027': 'LP3nV76f2TA',
  'p-028': '55QWhIvNMko',
  'p-029': 'lD1OLuSf9GU',
  'p-030': 'R3l4R22z5oM',
  'p-031': '8w4VcLfa-Q8',
  'p-032': 'xd9HdcR-V6E',
  'p-033': 'dZ4mueFlfqs',
  'p-034': 'w_DJAGgmZPA',
  'p-035': 'Yj66BIpxYF8',
  'p-036': 'NfSSUjX7440',
  'p-037': 'wcoXr9o83o8',
  'p-038': 'b0yQi11cHuc',
  'p-039': 'V1ZY56DKoH0',
  'p-040': 'Fo1ZKpX4-f8',
};

const categoryProductPhotoIds: Record<PhotoCategory, readonly string[]> = {
  laptops: ['p-001', 'p-002', 'p-021', 'p-022'],
  monitors: ['p-003', 'p-004', 'p-023', 'p-024'],
  headphones: ['p-005', 'p-006', 'p-029', 'p-030'],
  keyboards: ['p-007', 'p-008', 'p-025', 'p-026'],
  mice: ['p-009', 'p-010', 'p-027', 'p-028'],
  smartwatches: ['p-011', 'p-012', 'p-031', 'p-032'],
  speakers: ['p-013', 'p-014', 'p-033', 'p-034'],
  webcams: ['p-015', 'p-016', 'p-035', 'p-036'],
  'desk-accessories': ['p-017', 'p-018', 'p-037', 'p-038'],
  'charging-accessories': ['p-019', 'p-020', 'p-039', 'p-040'],
};

function categoryPhoto(category: PhotoCategory, seed: string, angle = 0): string {
  const photos = categoryPhotoSets[category];
  const numericSeed = Number(seed.match(/\d+$/)?.[0] ?? 0);
  const photoId = photos[(numericSeed + angle) % photos.length];

  return `${photoBase}/${photoId}?auto=format&fit=crop&w=1200&q=92`;
}

function productPhoto(productId: string, view = 0): string {
  const photoId = productPhotoIds[productId];
  const imageWidth = view === 0 ? 1200 : view === 1 ? 1320 : 1080;
  const cropMode = view === 0 ? 'crop' : view === 1 ? 'fill' : 'max';
  const quality = view === 0 ? 92 : 88;

  if (photoId.startsWith('photo-')) {
    return `${photoBase}/${photoId}?auto=format&fit=${cropMode}&w=${imageWidth}&q=${quality}`;
  }

  return `https://unsplash.com/photos/${photoId}/download?force=true&w=${imageWidth}`;
}

function productGallery(productId: string, category: PhotoCategory): string[] {
  const categoryProductIds = categoryProductPhotoIds[category];
  const primaryIndex = categoryProductIds.indexOf(productId);
  const fallbackIndex = Number(productId.match(/\d+$/)?.[0] ?? 0) % categoryProductIds.length;
  const startIndex = primaryIndex >= 0 ? primaryIndex : fallbackIndex;
  const galleryProductIds = [
    productId,
    categoryProductIds[(startIndex + 1) % categoryProductIds.length],
    categoryProductIds[(startIndex + 2) % categoryProductIds.length],
  ];

  return galleryProductIds.map((galleryProductId, index) => productPhoto(galleryProductId, index));
}

const categories: readonly ProductCategory[] = [
  {
    id: 'laptops',
    name: 'Laptops',
    description: 'Thin performance notebooks for design, engineering, and travel.',
    imageUrl: categoryPhoto('laptops', 'category-laptops'),
    productCount: 4,
  },
  {
    id: 'monitors',
    name: 'Monitors',
    description: 'Color-accurate displays for focused creative and technical work.',
    imageUrl: categoryPhoto('monitors', 'category-monitors'),
    productCount: 4,
  },
  {
    id: 'headphones',
    name: 'Headphones',
    description: 'Immersive wireless audio with premium materials and long battery life.',
    imageUrl: categoryPhoto('headphones', 'category-headphones'),
    productCount: 4,
  },
  {
    id: 'keyboards',
    name: 'Keyboards',
    description: 'Low-profile and mechanical boards tuned for precise daily input.',
    imageUrl: categoryPhoto('keyboards', 'category-keyboards'),
    productCount: 4,
  },
  {
    id: 'mice',
    name: 'Mice',
    description: 'Ergonomic pointing tools for fast navigation and detailed control.',
    imageUrl: categoryPhoto('mice', 'category-mice'),
    productCount: 4,
  },
  {
    id: 'smartwatches',
    name: 'Smartwatches',
    description: 'Polished wearables for health tracking, calls, and daily planning.',
    imageUrl: categoryPhoto('smartwatches', 'category-smartwatches'),
    productCount: 4,
  },
  {
    id: 'speakers',
    name: 'Speakers',
    description: 'Compact and room-filling speakers with modern wireless connectivity.',
    imageUrl: categoryPhoto('speakers', 'category-speakers'),
    productCount: 4,
  },
  {
    id: 'webcams',
    name: 'Webcams',
    description: 'Sharp cameras and lighting for executive video calls and streaming.',
    imageUrl: categoryPhoto('webcams', 'category-webcams'),
    productCount: 4,
  },
  {
    id: 'desk-accessories',
    name: 'Desk Accessories',
    description: 'Finishing pieces that keep premium workstations tidy and intentional.',
    imageUrl: categoryPhoto('desk-accessories', 'category-desk-accessories'),
    productCount: 4,
  },
  {
    id: 'charging-accessories',
    name: 'Charging Accessories',
    description: 'Fast chargers, cables, and docks for modern multi-device setups.',
    imageUrl: categoryPhoto('charging-accessories', 'category-charging-accessories'),
    productCount: 4,
  },
];

const products: readonly Product[] = [
  {
    id: 'p-001',
    slug: 'aureon-luma-14',
    name: 'Aureon Luma 14',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description:
      'A 14-inch creator laptop with an aluminum chassis and vivid edge-to-edge display.',
    longDescription:
      'Built for founders, designers, and engineers who move between desk, studio, and client room, the Aureon Luma 14 balances premium materials with serious portable performance. Its high-brightness display, quiet cooling profile, and all-day battery make it a refined daily driver for complex workflows.',
    price: 1899,
    originalPrice: 2099,
    rating: 4.9,
    reviewCount: 328,
    imageUrl: productPhoto('p-001'),
    gallery: productGallery('p-001', 'laptops'),
    badge: 'Bestseller',
    isFeatured: true,
    stock: 14,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-1tb', label: 'Finish', value: 'Graphite / 1TB', inStock: true },
      { id: 'silver-1tb', label: 'Finish', value: 'Silver / 1TB', inStock: true },
      { id: 'midnight-2tb', label: 'Finish', value: 'Midnight / 2TB', inStock: false },
    ],
    specs: [
      { label: 'Display', value: '14.2 in 120Hz micro-edge panel' },
      { label: 'Memory', value: '32GB unified high-bandwidth memory' },
      { label: 'Storage', value: '1TB NVMe solid-state drive' },
      { label: 'Battery', value: 'Up to 18 hours' },
    ],
    relatedProductIds: ['p-002', 'p-003', 'p-019'],
  },
  {
    id: 'p-002',
    slug: 'nomadix-pro-16',
    name: 'Nomadix Pro 16',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description: 'A powerful 16-inch workstation notebook tuned for 3D, code, and video timelines.',
    longDescription:
      'Nomadix Pro 16 is the portable workstation for teams that need desktop-class capability without visual bulk. A wide-gamut display, dedicated creator graphics, and a rigid magnesium frame give it the speed and presence expected from a premium electronics flagship.',
    price: 2499,
    rating: 4.8,
    reviewCount: 214,
    imageUrl: productPhoto('p-002'),
    gallery: productGallery('p-002', 'laptops'),
    badge: 'New',
    isFeatured: true,
    stock: 7,
    stockStatus: 'Low stock',
    variants: [
      { id: 'onyx-2tb', label: 'Configuration', value: 'Onyx / 2TB', inStock: true },
      { id: 'titanium-2tb', label: 'Configuration', value: 'Titanium / 2TB', inStock: true },
    ],
    specs: [
      { label: 'Display', value: '16 in 3.2K color-calibrated panel' },
      { label: 'Graphics', value: 'Creator-class 12GB GPU' },
      { label: 'Memory', value: '64GB performance memory' },
      { label: 'Ports', value: 'Thunderbolt-class USB-C, HDMI, SD reader' },
    ],
    relatedProductIds: ['p-001', 'p-003', 'p-004'],
  },
  {
    id: 'p-003',
    slug: 'prismview-32-studio',
    name: 'PrismView 32 Studio',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A 32-inch 6K studio monitor with a slim metal stand and factory calibration.',
    longDescription:
      'PrismView 32 Studio gives creative teams a spacious, color-accurate canvas with high pixel density and a quiet premium silhouette. It is designed for detail-heavy editing, interface design, and multitasking across demanding desktop workflows.',
    price: 1199,
    originalPrice: 1399,
    rating: 4.9,
    reviewCount: 186,
    imageUrl: productPhoto('p-003'),
    gallery: productGallery('p-003', 'monitors'),
    badge: 'Sale',
    isFeatured: true,
    stock: 19,
    stockStatus: 'In stock',
    variants: [
      { id: 'silver-stand', label: 'Stand', value: 'Silver tilt stand', inStock: true },
      { id: 'black-arm', label: 'Stand', value: 'Black monitor arm', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '6016 x 3384' },
      { label: 'Refresh rate', value: '75Hz' },
      { label: 'Color', value: '98% DCI-P3 coverage' },
      { label: 'Connectivity', value: 'USB-C with 96W charging' },
    ],
    relatedProductIds: ['p-004', 'p-001', 'p-017'],
  },
  {
    id: 'p-004',
    slug: 'arcscale-27-gaming',
    name: 'ArcScale 27 Performance',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A 27-inch 4K performance display with fast refresh and ultra-thin bezels.',
    longDescription:
      'ArcScale 27 Performance brings speed and clarity to premium desks, pairing a crisp 4K panel with fluid motion handling for gaming, trading dashboards, and high-density productivity. The minimal stand keeps the workstation clean and adjustable.',
    price: 699,
    rating: 4.7,
    reviewCount: 143,
    imageUrl: productPhoto('p-004'),
    gallery: productGallery('p-004', 'monitors'),
    badge: 'Limited',
    isFeatured: false,
    stock: 9,
    stockStatus: 'Low stock',
    variants: [
      { id: 'matte-black', label: 'Finish', value: 'Matte black', inStock: true },
      { id: 'frost-white', label: 'Finish', value: 'Frost white', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '3840 x 2160' },
      { label: 'Refresh rate', value: '144Hz' },
      { label: 'Response', value: '1ms gray-to-gray' },
      { label: 'Sync', value: 'Adaptive frame sync' },
    ],
    relatedProductIds: ['p-003', 'p-010', 'p-012'],
  },
  {
    id: 'p-005',
    slug: 'solace-air-headphones',
    name: 'Solace Air Headphones',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description: 'Wireless over-ear headphones with adaptive noise control and soft lambskin pads.',
    longDescription:
      'Solace Air Headphones are tuned for long sessions in open offices, flights, and focused deep work. Adaptive noise control, low-latency wireless audio, and premium cushions create a calm, detailed listening experience without shouting for attention.',
    price: 379,
    originalPrice: 429,
    rating: 4.8,
    reviewCount: 412,
    imageUrl: productPhoto('p-005'),
    gallery: productGallery('p-005', 'headphones'),
    badge: 'Bestseller',
    isFeatured: true,
    stock: 31,
    stockStatus: 'In stock',
    variants: [
      { id: 'carbon', label: 'Color', value: 'Carbon', inStock: true },
      { id: 'sandstone', label: 'Color', value: 'Sandstone', inStock: true },
      { id: 'deep-navy', label: 'Color', value: 'Deep navy', inStock: true },
    ],
    specs: [
      { label: 'Battery', value: '46 hours with ANC' },
      { label: 'Drivers', value: '42mm bio-cellulose drivers' },
      { label: 'Charging', value: 'USB-C fast charge' },
      { label: 'Microphones', value: '6 beamforming microphones' },
    ],
    relatedProductIds: ['p-006', 'p-013', 'p-014'],
  },
  {
    id: 'p-006',
    slug: 'aether-buds-pro',
    name: 'Aether Buds Pro',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description:
      'Compact premium earbuds with spatial audio, call isolation, and wireless charging.',
    longDescription:
      'Aether Buds Pro are made for commuters and hybrid teams who want polished sound in a pocketable form. The case supports quick wireless top-ups, while intelligent microphones keep calls crisp in cafes, airports, and shared spaces.',
    price: 229,
    rating: 4.6,
    reviewCount: 267,
    imageUrl: productPhoto('p-006'),
    gallery: productGallery('p-006', 'headphones'),
    badge: 'New',
    isFeatured: false,
    stock: 42,
    stockStatus: 'In stock',
    variants: [
      { id: 'porcelain', label: 'Color', value: 'Porcelain', inStock: true },
      { id: 'graphite', label: 'Color', value: 'Graphite', inStock: true },
    ],
    specs: [
      { label: 'Battery', value: '8 hours, 32 hours with case' },
      { label: 'Water resistance', value: 'IPX5' },
      { label: 'Audio', value: 'Spatial mode with head tracking' },
      { label: 'Case', value: 'Qi wireless charging' },
    ],
    relatedProductIds: ['p-005', 'p-019', 'p-020'],
  },
  {
    id: 'p-007',
    slug: 'keystone-flow-75',
    name: 'Keystone Flow 75',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A hot-swappable 75% mechanical keyboard with gasket mount and premium caps.',
    longDescription:
      'Keystone Flow 75 gives tactile keyboard fans a quieter, more refined board for serious work. The compact layout keeps core keys close, while hot-swap sockets, tuned stabilizers, and sculpted keycaps make it easy to customize without rebuilding the desk.',
    price: 189,
    rating: 4.8,
    reviewCount: 153,
    imageUrl: productPhoto('p-007'),
    gallery: productGallery('p-007', 'keyboards'),
    badge: 'Limited',
    isFeatured: true,
    stock: 12,
    stockStatus: 'Low stock',
    variants: [
      { id: 'linear-mist', label: 'Switch', value: 'Linear mist', inStock: true },
      { id: 'tactile-ember', label: 'Switch', value: 'Tactile ember', inStock: true },
      { id: 'silent-ash', label: 'Switch', value: 'Silent ash', inStock: false },
    ],
    specs: [
      { label: 'Layout', value: '75% compact with function row' },
      { label: 'Connection', value: 'USB-C, Bluetooth, 2.4GHz' },
      { label: 'Mount', value: 'Double gasket isolation' },
      { label: 'Battery', value: '4000mAh rechargeable' },
    ],
    relatedProductIds: ['p-008', 'p-009', 'p-017'],
  },
  {
    id: 'p-008',
    slug: 'typecraft-slim',
    name: 'TypeCraft Slim',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A low-profile wireless keyboard with quiet scissor switches and metal top case.',
    longDescription:
      'TypeCraft Slim is built for polished executive desks where quiet typing, clean lines, and instant device switching matter. It pairs with three devices, charges over USB-C, and keeps a precise key feel in a thin aluminum profile.',
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviewCount: 98,
    imageUrl: productPhoto('p-008'),
    gallery: productGallery('p-008', 'keyboards'),
    badge: 'Sale',
    isFeatured: false,
    stock: 26,
    stockStatus: 'In stock',
    variants: [
      { id: 'space-gray', label: 'Finish', value: 'Space gray', inStock: true },
      { id: 'arctic', label: 'Finish', value: 'Arctic silver', inStock: true },
    ],
    specs: [
      { label: 'Layout', value: 'Full-size low profile' },
      { label: 'Connection', value: 'Bluetooth multi-device' },
      { label: 'Battery', value: 'Up to 4 months' },
      { label: 'Build', value: 'Aluminum top plate' },
    ],
    relatedProductIds: ['p-007', 'p-010', 'p-018'],
  },
  {
    id: 'p-009',
    slug: 'vector-grip-mouse',
    name: 'Vector Grip Mouse',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'An ergonomic wireless mouse with glass-smooth feet and precision tracking.',
    longDescription:
      'Vector Grip Mouse is shaped for long workdays without looking clinical. It combines a high-resolution sensor, quiet clicks, and thoughtful side controls in a premium shell that belongs beside a flagship laptop or workstation display.',
    price: 99,
    rating: 4.7,
    reviewCount: 221,
    imageUrl: productPhoto('p-009'),
    gallery: productGallery('p-009', 'mice'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 38,
    stockStatus: 'In stock',
    variants: [
      { id: 'right-carbon', label: 'Grip', value: 'Right hand / Carbon', inStock: true },
      { id: 'right-silver', label: 'Grip', value: 'Right hand / Silver', inStock: true },
    ],
    specs: [
      { label: 'Sensor', value: '26K precision optical sensor' },
      { label: 'Buttons', value: '7 programmable controls' },
      { label: 'Battery', value: '90 days per charge' },
      { label: 'Weight', value: '78g' },
    ],
    relatedProductIds: ['p-010', 'p-007', 'p-017'],
  },
  {
    id: 'p-010',
    slug: 'nimbus-track-mouse',
    name: 'Nimbus Track Mouse',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'A sculpted productivity mouse with magnetic scroll wheel and gesture controls.',
    longDescription:
      'Nimbus Track Mouse is designed for analysts, editors, and builders who move through dense screens all day. Its magnetic wheel shifts between precise and free-spin scrolling, while gesture zones keep navigation fluid across large canvases.',
    price: 119,
    originalPrice: 139,
    rating: 4.6,
    reviewCount: 176,
    imageUrl: productPhoto('p-010'),
    gallery: productGallery('p-010', 'mice'),
    badge: 'Sale',
    isFeatured: false,
    stock: 23,
    stockStatus: 'In stock',
    variants: [
      { id: 'black', label: 'Color', value: 'Black', inStock: true },
      { id: 'pearl', label: 'Color', value: 'Pearl', inStock: true },
    ],
    specs: [
      { label: 'Scroll', value: 'Magnetic adaptive wheel' },
      { label: 'Connection', value: 'Bluetooth and 2.4GHz receiver' },
      { label: 'Charging', value: 'USB-C quick charge' },
      { label: 'Surface', value: 'Tracks on glass' },
    ],
    relatedProductIds: ['p-009', 'p-008', 'p-004'],
  },
  {
    id: 'p-011',
    slug: 'tempo-watch-slate',
    name: 'Tempo Watch Slate',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description:
      'A refined smartwatch with stainless casing, health sensors, and always-on display.',
    longDescription:
      'Tempo Watch Slate blends daily wellness tracking with a clean dress-watch profile. It handles calls, calendar alerts, workouts, and recovery trends while keeping the materials, strap options, and interface firmly premium.',
    price: 449,
    rating: 4.7,
    reviewCount: 244,
    imageUrl: productPhoto('p-011'),
    gallery: productGallery('p-011', 'smartwatches'),
    badge: 'New',
    isFeatured: true,
    stock: 17,
    stockStatus: 'In stock',
    variants: [
      { id: 'slate-42', label: 'Case', value: 'Slate steel / 42mm', inStock: true },
      { id: 'champagne-42', label: 'Case', value: 'Champagne steel / 42mm', inStock: true },
    ],
    specs: [
      { label: 'Display', value: 'Always-on AMOLED' },
      { label: 'Sensors', value: 'ECG, oxygen, skin temperature' },
      { label: 'Battery', value: 'Up to 5 days' },
      { label: 'Water rating', value: '5 ATM' },
    ],
    relatedProductIds: ['p-012', 'p-006', 'p-020'],
  },
  {
    id: 'p-012',
    slug: 'pulseband-ultra',
    name: 'PulseBand Ultra',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description: 'A rugged titanium fitness watch with dual-frequency GPS and sapphire glass.',
    longDescription:
      'PulseBand Ultra is made for serious training without sacrificing a premium interface. Dual-frequency GPS, sapphire glass, and a high-contrast display support long outdoor sessions, while recovery metrics keep the experience useful at the desk too.',
    price: 599,
    rating: 4.8,
    reviewCount: 189,
    imageUrl: productPhoto('p-012'),
    gallery: productGallery('p-012', 'smartwatches'),
    badge: 'Limited',
    isFeatured: false,
    stock: 5,
    stockStatus: 'Low stock',
    variants: [
      { id: 'titanium-black', label: 'Band', value: 'Titanium / Black trail', inStock: true },
      { id: 'titanium-orange', label: 'Band', value: 'Titanium / Signal orange', inStock: true },
    ],
    specs: [
      { label: 'Case', value: 'Titanium with sapphire crystal' },
      { label: 'GPS', value: 'Dual-frequency positioning' },
      { label: 'Battery', value: 'Up to 12 days' },
      { label: 'Training', value: 'Recovery, routes, intervals' },
    ],
    relatedProductIds: ['p-011', 'p-004', 'p-013'],
  },
  {
    id: 'p-013',
    slug: 'halo-room-speaker',
    name: 'Halo Room Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A compact room speaker with rich stereo pairing and fabric-wrapped acoustics.',
    longDescription:
      'Halo Room Speaker fills offices, kitchens, and studio corners with warm, balanced sound from a compact enclosure. It supports multi-room playback, voice-safe privacy controls, and stereo pairing for a more expansive premium listening setup.',
    price: 249,
    rating: 4.6,
    reviewCount: 138,
    imageUrl: productPhoto('p-013'),
    gallery: productGallery('p-013', 'speakers'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 28,
    stockStatus: 'In stock',
    variants: [
      { id: 'charcoal', label: 'Color', value: 'Charcoal weave', inStock: true },
      { id: 'linen', label: 'Color', value: 'Linen weave', inStock: true },
    ],
    specs: [
      { label: 'Audio', value: '360-degree room tuning' },
      { label: 'Connection', value: 'Wi-Fi, Bluetooth, line-in' },
      { label: 'Pairing', value: 'Stereo and multi-room' },
      { label: 'Controls', value: 'Touch top panel' },
    ],
    relatedProductIds: ['p-014', 'p-005', 'p-006'],
  },
  {
    id: 'p-014',
    slug: 'canto-mini-speaker',
    name: 'Canto Mini Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A travel-ready Bluetooth speaker with anodized shell and bold sound.',
    longDescription:
      'Canto Mini Speaker is the polished portable speaker for hotel rooms, patios, and compact desks. Its anodized shell, water resistance, and surprisingly deep driver array make it feel considered instead of disposable.',
    price: 139,
    originalPrice: 169,
    rating: 4.5,
    reviewCount: 104,
    imageUrl: productPhoto('p-014'),
    gallery: productGallery('p-014', 'speakers'),
    badge: 'Sale',
    isFeatured: false,
    stock: 36,
    stockStatus: 'In stock',
    variants: [
      { id: 'ink', label: 'Color', value: 'Ink', inStock: true },
      { id: 'clay', label: 'Color', value: 'Clay', inStock: true },
      { id: 'mist', label: 'Color', value: 'Mist', inStock: false },
    ],
    specs: [
      { label: 'Battery', value: '18 hours playback' },
      { label: 'Rating', value: 'IP67 dust and water resistance' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pairing', value: 'Dual-speaker stereo mode' },
    ],
    relatedProductIds: ['p-013', 'p-005', 'p-020'],
  },
  {
    id: 'p-015',
    slug: 'clarity-cam-4k',
    name: 'ClarityCam 4K',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A 4K webcam with glass optics, smart framing, and built-in privacy shutter.',
    longDescription:
      'ClarityCam 4K upgrades remote presence with crisp detail, balanced exposure, and a camera body that looks appropriate on a premium monitor. Smart framing keeps the shot composed, while the hardware shutter gives quick visual privacy.',
    price: 199,
    rating: 4.7,
    reviewCount: 132,
    imageUrl: productPhoto('p-015'),
    gallery: productGallery('p-015', 'webcams'),
    badge: 'New',
    isFeatured: false,
    stock: 22,
    stockStatus: 'In stock',
    variants: [
      { id: 'monitor-mount', label: 'Mount', value: 'Monitor mount', inStock: true },
      { id: 'tripod-kit', label: 'Mount', value: 'Tripod creator kit', inStock: true },
    ],
    specs: [
      { label: 'Video', value: '4K at 30fps, 1080p at 60fps' },
      { label: 'Lens', value: 'Glass lens with 90-degree FOV' },
      { label: 'Audio', value: 'Dual noise-reducing microphones' },
      { label: 'Privacy', value: 'Integrated shutter' },
    ],
    relatedProductIds: ['p-016', 'p-003', 'p-018'],
  },
  {
    id: 'p-016',
    slug: 'studioframe-hd',
    name: 'StudioFrame HD',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A slim 1080p webcam with soft fill light and automatic white balance.',
    longDescription:
      'StudioFrame HD is the clean everyday camera for polished calls without a heavy creator rig. A soft fill light, automatic white balance, and magnetic mount make it simple to look composed from compact workstations.',
    price: 119,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 87,
    imageUrl: productPhoto('p-016'),
    gallery: productGallery('p-016', 'webcams'),
    badge: 'Sale',
    isFeatured: false,
    stock: 0,
    stockStatus: 'Sold out',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: false },
      { id: 'silver', label: 'Finish', value: 'Silver', inStock: false },
    ],
    specs: [
      { label: 'Video', value: '1080p at 60fps' },
      { label: 'Lighting', value: 'Adjustable soft LED ring' },
      { label: 'Mount', value: 'Magnetic monitor mount' },
      { label: 'Connection', value: 'USB-C' },
    ],
    relatedProductIds: ['p-015', 'p-004', 'p-007'],
  },
  {
    id: 'p-017',
    slug: 'axis-desk-dock',
    name: 'Axis Desk Dock',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A machined aluminum desk dock with cable routing and weighted device channels.',
    longDescription:
      'Axis Desk Dock keeps premium setups intentional by organizing a laptop, tablet, phone, and active cables in one weighted aluminum base. The finish pairs cleanly with high-end displays and helps busy workstations stay presentation-ready.',
    price: 149,
    rating: 4.6,
    reviewCount: 119,
    imageUrl: productPhoto('p-017'),
    gallery: productGallery('p-017', 'desk-accessories'),
    badge: 'Limited',
    isFeatured: false,
    stock: 16,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: true },
      { id: 'natural', label: 'Finish', value: 'Natural aluminum', inStock: true },
    ],
    specs: [
      { label: 'Material', value: 'CNC aluminum with silicone rails' },
      { label: 'Capacity', value: 'Laptop, tablet, phone, cables' },
      { label: 'Weight', value: '2.4 lb weighted base' },
      { label: 'Cable routing', value: 'Four rear channels' },
    ],
    relatedProductIds: ['p-018', 'p-019', 'p-003'],
  },
  {
    id: 'p-018',
    slug: 'focuspad-pro-mat',
    name: 'FocusPad Pro Mat',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A premium desk mat with vegan leather surface and hidden magnetic cable guides.',
    longDescription:
      'FocusPad Pro Mat gives keyboards, mice, and devices a consistent working surface with a refined executive look. Hidden magnetic cable guides and stitched edges make the desk feel finished while staying durable enough for daily use.',
    price: 89,
    rating: 4.5,
    reviewCount: 203,
    imageUrl: productPhoto('p-018'),
    gallery: productGallery('p-018', 'desk-accessories'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 44,
    stockStatus: 'In stock',
    variants: [
      { id: 'stone', label: 'Color', value: 'Stone', inStock: true },
      { id: 'graphite', label: 'Color', value: 'Graphite', inStock: true },
      { id: 'walnut', label: 'Color', value: 'Walnut', inStock: true },
    ],
    specs: [
      { label: 'Size', value: '31.5 x 15.7 in' },
      { label: 'Surface', value: 'Water-resistant vegan leather' },
      { label: 'Base', value: 'Micro-suction non-slip backing' },
      { label: 'Included', value: '2 magnetic cable guides' },
    ],
    relatedProductIds: ['p-017', 'p-008', 'p-009'],
  },
  {
    id: 'p-019',
    slug: 'voltstack-140w-gan',
    name: 'VoltStack 140W GaN',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A compact 140W GaN charger with three USB-C ports and intelligent power sharing.',
    longDescription:
      'VoltStack 140W GaN replaces a bag full of chargers with a single premium brick for laptops, tablets, phones, and headphones. Intelligent power sharing routes wattage where it is needed and keeps the housing compact for travel.',
    price: 119,
    originalPrice: 139,
    rating: 4.8,
    reviewCount: 302,
    imageUrl: productPhoto('p-019'),
    gallery: productGallery('p-019', 'charging-accessories'),
    badge: 'Sale',
    isFeatured: true,
    stock: 52,
    stockStatus: 'In stock',
    variants: [
      { id: 'us-plug', label: 'Plug', value: 'US folding plug', inStock: true },
      { id: 'travel-kit', label: 'Plug', value: 'Global travel kit', inStock: true },
    ],
    specs: [
      { label: 'Output', value: '140W max shared' },
      { label: 'Ports', value: '3 USB-C, 1 USB-A' },
      { label: 'Technology', value: 'GaN power architecture' },
      { label: 'Safety', value: 'Thermal and surge protection' },
    ],
    relatedProductIds: ['p-020', 'p-001', 'p-017'],
  },
  {
    id: 'p-020',
    slug: 'fluxline-magnetic-cable-kit',
    name: 'FluxLine Magnetic Cable Kit',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A braided USB-C cable kit with magnetic desk anchors and premium metal tips.',
    longDescription:
      'FluxLine Magnetic Cable Kit keeps charging points exactly where you expect them. Braided high-output cables, magnetic anchors, and color-coded metal tips make the kit practical for desks, travel pouches, and bedside stations.',
    price: 59,
    rating: 4.6,
    reviewCount: 158,
    imageUrl: productPhoto('p-020'),
    gallery: productGallery('p-020', 'charging-accessories'),
    badge: 'New',
    isFeatured: false,
    stock: 67,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-kit', label: 'Color', value: 'Graphite kit', inStock: true },
      { id: 'silver-kit', label: 'Color', value: 'Silver kit', inStock: true },
    ],
    specs: [
      { label: 'Cables', value: '3 braided USB-C cables' },
      { label: 'Power', value: 'Up to 100W charging' },
      { label: 'Data', value: '10Gbps transfer support' },
      { label: 'Included', value: '4 magnetic cable anchors' },
    ],
    relatedProductIds: ['p-019', 'p-006', 'p-014'],
  },
  {
    id: 'p-021',
    slug: 'aureon-luma-air-13',
    name: 'Aureon Luma Air 13',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description: 'An ultralight 13-inch notebook with silent cooling and an all-metal frame.',
    longDescription:
      'Aureon Luma Air 13 is the travel-focused laptop in the Vertex edit, built for executives, founders, and students who want premium performance without weight. It keeps the same refined display and keyboard feel as the larger Luma line, but trims the footprint for daily carry.',
    price: 1499,
    rating: 4.7,
    reviewCount: 146,
    imageUrl: productPhoto('p-021'),
    gallery: productGallery('p-021', 'laptops'),
    badge: 'New',
    isFeatured: false,
    stock: 21,
    stockStatus: 'In stock',
    variants: [
      { id: 'mist-512', label: 'Configuration', value: 'Mist / 512GB', inStock: true },
      { id: 'graphite-1tb', label: 'Configuration', value: 'Graphite / 1TB', inStock: true },
    ],
    specs: [
      { label: 'Display', value: '13.4 in 2.8K low-glare panel' },
      { label: 'Weight', value: '2.3 lb aluminum body' },
      { label: 'Memory', value: '24GB performance memory' },
      { label: 'Battery', value: 'Up to 20 hours' },
    ],
    relatedProductIds: ['p-001', 'p-022', 'p-039'],
  },
  {
    id: 'p-022',
    slug: 'forgebook-studio-15',
    name: 'ForgeBook Studio 15',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description: 'A 15-inch mobile studio laptop for editing, rendering, and multi-app workflows.',
    longDescription:
      'ForgeBook Studio 15 is tuned for creators who need more sustained performance than an ultraportable can provide. A high-refresh OLED-class panel, dedicated media engine, and quiet vapor cooling make it a polished workstation for video timelines, design systems, and 3D previews.',
    price: 2199,
    originalPrice: 2399,
    rating: 4.8,
    reviewCount: 172,
    imageUrl: productPhoto('p-022'),
    gallery: productGallery('p-022', 'laptops'),
    badge: 'Sale',
    isFeatured: false,
    stock: 10,
    stockStatus: 'Low stock',
    variants: [
      { id: 'black-1tb', label: 'Configuration', value: 'Obsidian / 1TB', inStock: true },
      { id: 'black-2tb', label: 'Configuration', value: 'Obsidian / 2TB', inStock: true },
    ],
    specs: [
      { label: 'Display', value: '15.6 in 120Hz creator panel' },
      { label: 'Graphics', value: 'Studio-class 10GB graphics' },
      { label: 'Cooling', value: 'Low-noise vapor chamber' },
      { label: 'Ports', value: 'USB-C, HDMI, SD, audio' },
    ],
    relatedProductIds: ['p-002', 'p-023', 'p-024'],
  },
  {
    id: 'p-023',
    slug: 'prismview-ultrawide-40',
    name: 'PrismView Ultrawide 40',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A curved 40-inch ultrawide display for timelines, dashboards, and code.',
    longDescription:
      'PrismView Ultrawide 40 creates a seamless panoramic workspace without the clutter of dual monitors. It is built for creators, analysts, and developers who want expansive horizontal room with premium color tuning and single-cable laptop docking.',
    price: 1599,
    rating: 4.9,
    reviewCount: 121,
    imageUrl: productPhoto('p-023'),
    gallery: productGallery('p-023', 'monitors'),
    badge: 'Limited',
    isFeatured: true,
    stock: 6,
    stockStatus: 'Low stock',
    variants: [
      { id: 'graphite-stand', label: 'Stand', value: 'Graphite ergonomic stand', inStock: true },
      { id: 'vesa-kit', label: 'Stand', value: 'VESA creator kit', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '5120 x 2160 ultrawide' },
      { label: 'Curve', value: '2500R gentle radius' },
      { label: 'Docking', value: 'USB-C with 100W charging' },
      { label: 'Color', value: '99% DCI-P3 factory tuned' },
    ],
    relatedProductIds: ['p-003', 'p-024', 'p-022'],
  },
  {
    id: 'p-024',
    slug: 'arcscale-ultrawide-34',
    name: 'ArcScale Ultrawide 34',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A fast 34-inch ultrawide monitor with crisp motion and deep contrast.',
    longDescription:
      'ArcScale Ultrawide 34 is the premium performance display for users who split time between immersive gaming, product work, and market dashboards. Its high refresh rate and clean industrial stand keep the experience sharp without turning the desk into a gaming rig.',
    price: 899,
    originalPrice: 1049,
    rating: 4.7,
    reviewCount: 204,
    imageUrl: productPhoto('p-024'),
    gallery: productGallery('p-024', 'monitors'),
    badge: 'Sale',
    isFeatured: false,
    stock: 18,
    stockStatus: 'In stock',
    variants: [
      { id: 'matte-black', label: 'Finish', value: 'Matte black', inStock: true },
      { id: 'ice-gray', label: 'Finish', value: 'Ice gray', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '3440 x 1440' },
      { label: 'Refresh rate', value: '175Hz adaptive' },
      { label: 'Panel', value: 'Quantum contrast display' },
      { label: 'Response', value: '0.8ms motion mode' },
    ],
    relatedProductIds: ['p-004', 'p-023', 'p-010'],
  },
  {
    id: 'p-025',
    slug: 'keystone-atelier-65',
    name: 'Keystone Atelier 65',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A compact 65% mechanical keyboard with ceramic caps and tuned acoustics.',
    longDescription:
      'Keystone Atelier 65 is a refined typing instrument for compact desks and creators who care about sound, feel, and materials. Ceramic-feel keycaps, damped internals, and wireless multi-device support make it premium without unnecessary visual noise.',
    price: 249,
    rating: 4.8,
    reviewCount: 93,
    imageUrl: productPhoto('p-025'),
    gallery: productGallery('p-025', 'keyboards'),
    badge: 'Limited',
    isFeatured: false,
    stock: 8,
    stockStatus: 'Low stock',
    variants: [
      { id: 'linear-porcelain', label: 'Switch', value: 'Linear porcelain', inStock: true },
      { id: 'tactile-graphite', label: 'Switch', value: 'Tactile graphite', inStock: true },
    ],
    specs: [
      { label: 'Layout', value: '65% compact aluminum frame' },
      { label: 'Mount', value: 'Leaf-spring gasket mount' },
      { label: 'Connection', value: 'USB-C, Bluetooth, 2.4GHz' },
      { label: 'Keycaps', value: 'Ceramic-touch PBT caps' },
    ],
    relatedProductIds: ['p-007', 'p-026', 'p-027'],
  },
  {
    id: 'p-026',
    slug: 'typecraft-number-pad',
    name: 'TypeCraft Number Pad',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A wireless mechanical number pad for finance, CAD, and spreadsheet workflows.',
    longDescription:
      'TypeCraft Number Pad adds precision input only when your workflow needs it. The slim aluminum body pairs with full keyboards or compact boards, making it useful for analysts, architects, and operators who want flexibility without a permanent full-size layout.',
    price: 89,
    rating: 4.5,
    reviewCount: 74,
    imageUrl: productPhoto('p-026'),
    gallery: productGallery('p-026', 'keyboards'),
    badge: 'New',
    isFeatured: false,
    stock: 33,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: true },
      { id: 'silver', label: 'Finish', value: 'Silver', inStock: true },
    ],
    specs: [
      { label: 'Layout', value: '21-key number pad' },
      { label: 'Switches', value: 'Low-noise tactile mechanical' },
      { label: 'Battery', value: '3 months per charge' },
      { label: 'Pairing', value: 'Three-device memory' },
    ],
    relatedProductIds: ['p-008', 'p-025', 'p-010'],
  },
  {
    id: 'p-027',
    slug: 'vector-air-mouse',
    name: 'Vector Air Mouse',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'A featherweight wireless mouse with premium coating and esports-grade tracking.',
    longDescription:
      'Vector Air Mouse trims weight while keeping the premium finish expected from a modern workstation accessory. It is fast enough for competitive play, precise enough for design work, and restrained enough for a polished office desk.',
    price: 139,
    rating: 4.7,
    reviewCount: 164,
    imageUrl: productPhoto('p-027'),
    gallery: productGallery('p-027', 'mice'),
    badge: 'New',
    isFeatured: false,
    stock: 25,
    stockStatus: 'In stock',
    variants: [
      { id: 'frost', label: 'Color', value: 'Frost', inStock: true },
      { id: 'carbon', label: 'Color', value: 'Carbon', inStock: true },
    ],
    specs: [
      { label: 'Weight', value: '54g lightweight shell' },
      { label: 'Sensor', value: '30K precision optical sensor' },
      { label: 'Polling', value: 'Up to 4K wireless polling' },
      { label: 'Feet', value: 'Glass-smooth PTFE skates' },
    ],
    relatedProductIds: ['p-009', 'p-028', 'p-025'],
  },
  {
    id: 'p-028',
    slug: 'nimbus-vertical-pro',
    name: 'Nimbus Vertical Pro',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'A sculpted vertical mouse for ergonomic control across long work sessions.',
    longDescription:
      'Nimbus Vertical Pro is designed for people who spend hours moving through dense interfaces. A natural hand angle, silent switches, and app-specific shortcuts make it a premium productivity tool for design, research, support, and operations teams.',
    price: 129,
    originalPrice: 149,
    rating: 4.6,
    reviewCount: 137,
    imageUrl: productPhoto('p-028'),
    gallery: productGallery('p-028', 'mice'),
    badge: 'Sale',
    isFeatured: false,
    stock: 19,
    stockStatus: 'In stock',
    variants: [
      { id: 'right-graphite', label: 'Grip', value: 'Right hand / Graphite', inStock: true },
      { id: 'left-graphite', label: 'Grip', value: 'Left hand / Graphite', inStock: true },
    ],
    specs: [
      { label: 'Angle', value: '57-degree ergonomic posture' },
      { label: 'Buttons', value: '8 programmable controls' },
      { label: 'Scroll', value: 'Dual-mode precision wheel' },
      { label: 'Battery', value: '120 days per charge' },
    ],
    relatedProductIds: ['p-010', 'p-027', 'p-018'],
  },
  {
    id: 'p-029',
    slug: 'solace-studio-headphones',
    name: 'Solace Studio Headphones',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description: 'Reference-inspired wireless headphones with lossless mode and plush isolation.',
    longDescription:
      'Solace Studio Headphones bring a more analytical tuning to the Vertex audio range. They are made for editing, focused listening, and long travel days, with a wired lossless mode, premium pads, and a restrained silhouette.',
    price: 499,
    rating: 4.9,
    reviewCount: 118,
    imageUrl: productPhoto('p-029'),
    gallery: productGallery('p-029', 'headphones'),
    badge: 'Limited',
    isFeatured: true,
    stock: 11,
    stockStatus: 'Low stock',
    variants: [
      { id: 'studio-black', label: 'Color', value: 'Studio black', inStock: true },
      { id: 'warm-silver', label: 'Color', value: 'Warm silver', inStock: true },
    ],
    specs: [
      { label: 'Drivers', value: '50mm planar-inspired drivers' },
      { label: 'Modes', value: 'Wireless ANC and wired lossless' },
      { label: 'Battery', value: '38 hours with ANC' },
      { label: 'Case', value: 'Rigid travel case included' },
    ],
    relatedProductIds: ['p-005', 'p-030', 'p-031'],
  },
  {
    id: 'p-030',
    slug: 'aether-buds-lite',
    name: 'Aether Buds Lite',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description: 'Minimal wireless earbuds with clean call quality and a pocketable matte case.',
    longDescription:
      'Aether Buds Lite deliver the essential premium earbud experience in a smaller package. They keep the fit, reliable connection, and refined case design, while simplifying advanced audio modes for a lower everyday price.',
    price: 149,
    originalPrice: 179,
    rating: 4.5,
    reviewCount: 211,
    imageUrl: productPhoto('p-030'),
    gallery: productGallery('p-030', 'headphones'),
    badge: 'Sale',
    isFeatured: false,
    stock: 48,
    stockStatus: 'In stock',
    variants: [
      { id: 'chalk', label: 'Color', value: 'Chalk', inStock: true },
      { id: 'ink', label: 'Color', value: 'Ink', inStock: true },
      { id: 'sage', label: 'Color', value: 'Sage', inStock: true },
    ],
    specs: [
      { label: 'Battery', value: '7 hours, 28 hours with case' },
      { label: 'Audio', value: 'Adaptive EQ' },
      { label: 'Microphones', value: 'Dual call isolation mics' },
      { label: 'Charging', value: 'USB-C quick charge case' },
    ],
    relatedProductIds: ['p-006', 'p-029', 'p-020'],
  },
  {
    id: 'p-031',
    slug: 'tempo-watch-classic',
    name: 'Tempo Watch Classic',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description: 'A slim smartwatch with a round display, steel case, and leather sport strap.',
    longDescription:
      'Tempo Watch Classic brings smart health tracking into a more traditional watch silhouette. It is designed for users who want calendar, wellness, and call controls without giving up a polished round case and refined strap options.',
    price: 399,
    rating: 4.6,
    reviewCount: 132,
    imageUrl: productPhoto('p-031'),
    gallery: productGallery('p-031', 'smartwatches'),
    badge: 'New',
    isFeatured: false,
    stock: 24,
    stockStatus: 'In stock',
    variants: [
      { id: 'steel-tan', label: 'Case', value: 'Steel / Tan hybrid', inStock: true },
      { id: 'black-black', label: 'Case', value: 'Black / Black sport', inStock: true },
    ],
    specs: [
      { label: 'Display', value: 'Round always-on AMOLED' },
      { label: 'Battery', value: 'Up to 7 days' },
      { label: 'Sensors', value: 'Heart, sleep, stress, oxygen' },
      { label: 'Compatibility', value: 'Cross-platform sync' },
    ],
    relatedProductIds: ['p-011', 'p-032', 'p-029'],
  },
  {
    id: 'p-032',
    slug: 'pulseband-core',
    name: 'PulseBand Core',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description: 'A lightweight fitness watch with AMOLED display and week-long battery.',
    longDescription:
      'PulseBand Core focuses on the features most athletes and commuters use every day: accurate workouts, long battery life, bright outdoor visibility, and simple notifications. It is light enough for sleep tracking but polished enough for the office.',
    price: 279,
    originalPrice: 329,
    rating: 4.5,
    reviewCount: 188,
    imageUrl: productPhoto('p-032'),
    gallery: productGallery('p-032', 'smartwatches'),
    badge: 'Sale',
    isFeatured: false,
    stock: 37,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-silicone', label: 'Band', value: 'Graphite silicone', inStock: true },
      { id: 'mist-silicone', label: 'Band', value: 'Mist silicone', inStock: true },
    ],
    specs: [
      { label: 'Weight', value: '34g lightweight case' },
      { label: 'Battery', value: 'Up to 9 days' },
      { label: 'Tracking', value: '120 workout modes' },
      { label: 'Water rating', value: '5 ATM swim-ready' },
    ],
    relatedProductIds: ['p-012', 'p-031', 'p-030'],
  },
  {
    id: 'p-033',
    slug: 'halo-arc-speaker',
    name: 'Halo Arc Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A premium portable speaker with room calibration and a curved aluminum body.',
    longDescription:
      'Halo Arc Speaker is portable enough for a shelf, studio, or patio, but tuned with the staging and clarity of a larger room system. Its curved aluminum body, fabric grille, and adaptive room calibration keep it aligned with premium interiors.',
    price: 329,
    rating: 4.7,
    reviewCount: 97,
    imageUrl: productPhoto('p-033'),
    gallery: productGallery('p-033', 'speakers'),
    badge: 'New',
    isFeatured: false,
    stock: 16,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-weave', label: 'Color', value: 'Graphite weave', inStock: true },
      { id: 'salt-weave', label: 'Color', value: 'Salt weave', inStock: true },
    ],
    specs: [
      { label: 'Audio', value: 'Adaptive room calibration' },
      { label: 'Battery', value: '22 hours portable playback' },
      { label: 'Connection', value: 'Wi-Fi, Bluetooth, USB-C audio' },
      { label: 'Build', value: 'Curved aluminum enclosure' },
    ],
    relatedProductIds: ['p-013', 'p-034', 'p-029'],
  },
  {
    id: 'p-034',
    slug: 'canto-field-speaker',
    name: 'Canto Field Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A rugged portable speaker with a woven strap and crisp outdoor projection.',
    longDescription:
      'Canto Field Speaker is built for premium portability: beach days, location shoots, travel, and desk overflow. The acoustic profile favors clear vocals and controlled bass, while the woven strap and sealed body make it easy to take anywhere.',
    price: 189,
    originalPrice: 219,
    rating: 4.6,
    reviewCount: 145,
    imageUrl: productPhoto('p-034'),
    gallery: productGallery('p-034', 'speakers'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 29,
    stockStatus: 'In stock',
    variants: [
      { id: 'black-strap', label: 'Color', value: 'Black / Graphite strap', inStock: true },
      { id: 'clay-strap', label: 'Color', value: 'Clay / Sand strap', inStock: true },
    ],
    specs: [
      { label: 'Rating', value: 'IP67 sealed body' },
      { label: 'Battery', value: '24 hours playback' },
      { label: 'Audio', value: 'Dual passive radiators' },
      { label: 'Carry', value: 'Removable woven strap' },
    ],
    relatedProductIds: ['p-014', 'p-033', 'p-030'],
  },
  {
    id: 'p-035',
    slug: 'claritycam-studio-bar',
    name: 'ClarityCam Studio Bar',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A premium video bar with 4K camera, beamforming audio, and soft desk lighting.',
    longDescription:
      'ClarityCam Studio Bar turns a workstation into a polished video room without separate camera, light, and microphone hardware. It is ideal for founders, recruiters, and remote teams who want a clean setup that looks intentional on every call.',
    price: 349,
    rating: 4.8,
    reviewCount: 86,
    imageUrl: productPhoto('p-035'),
    gallery: productGallery('p-035', 'webcams'),
    badge: 'Limited',
    isFeatured: false,
    stock: 9,
    stockStatus: 'Low stock',
    variants: [
      { id: 'graphite-bar', label: 'Finish', value: 'Graphite', inStock: true },
      { id: 'silver-bar', label: 'Finish', value: 'Silver', inStock: true },
    ],
    specs: [
      { label: 'Video', value: '4K HDR with smart crop' },
      { label: 'Audio', value: 'Four-mic beamforming array' },
      { label: 'Lighting', value: 'Adjustable soft fill light' },
      { label: 'Mount', value: 'Monitor and tripod support' },
    ],
    relatedProductIds: ['p-015', 'p-036', 'p-023'],
  },
  {
    id: 'p-036',
    slug: 'studioframe-pocket',
    name: 'StudioFrame Pocket',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A compact travel webcam with magnetic mount and crisp low-light tuning.',
    longDescription:
      'StudioFrame Pocket is made for consultants, sales teams, and students who move between desks but still want dependable video quality. The magnetic mount folds flat, and the sensor is tuned to keep skin tones natural in hotel rooms and shared offices.',
    price: 99,
    rating: 4.4,
    reviewCount: 112,
    imageUrl: productPhoto('p-036'),
    gallery: productGallery('p-036', 'webcams'),
    badge: 'New',
    isFeatured: false,
    stock: 41,
    stockStatus: 'In stock',
    variants: [
      { id: 'black', label: 'Finish', value: 'Black', inStock: true },
      { id: 'white', label: 'Finish', value: 'White', inStock: true },
    ],
    specs: [
      { label: 'Video', value: '1440p at 30fps' },
      { label: 'Mount', value: 'Fold-flat magnetic clip' },
      { label: 'Privacy', value: 'Slide shutter' },
      { label: 'Connection', value: 'Detachable USB-C cable' },
    ],
    relatedProductIds: ['p-016', 'p-035', 'p-021'],
  },
  {
    id: 'p-037',
    slug: 'axis-monitor-arm-pro',
    name: 'Axis Monitor Arm Pro',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A precision monitor arm with concealed cable routing and counterbalanced motion.',
    longDescription:
      'Axis Monitor Arm Pro brings workstation displays to the right ergonomic height while clearing desk space. The arm moves smoothly, hides cables cleanly, and supports both heavy ultrawides and lightweight studio monitors.',
    price: 219,
    rating: 4.7,
    reviewCount: 134,
    imageUrl: productPhoto('p-037'),
    gallery: productGallery('p-037', 'desk-accessories'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 27,
    stockStatus: 'In stock',
    variants: [
      { id: 'single-black', label: 'Model', value: 'Single / Black', inStock: true },
      { id: 'single-silver', label: 'Model', value: 'Single / Silver', inStock: true },
      { id: 'dual-black', label: 'Model', value: 'Dual / Black', inStock: false },
    ],
    specs: [
      { label: 'Support', value: 'Up to 40 in ultrawide' },
      { label: 'Motion', value: 'Counterbalanced gas spring' },
      { label: 'Routing', value: 'Internal cable channel' },
      { label: 'Mounting', value: 'Clamp and grommet included' },
    ],
    relatedProductIds: ['p-017', 'p-023', 'p-038'],
  },
  {
    id: 'p-038',
    slug: 'focus-riser-shelf',
    name: 'Focus Riser Shelf',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A minimalist monitor shelf with aluminum legs and a hidden accessory tray.',
    longDescription:
      'Focus Riser Shelf gives premium desks a layered, organized setup for monitors, docks, keyboards, and everyday objects. The hidden tray keeps small items out of sight, while the low profile improves ergonomics without dominating the desk.',
    price: 159,
    originalPrice: 189,
    rating: 4.6,
    reviewCount: 101,
    imageUrl: productPhoto('p-038'),
    gallery: productGallery('p-038', 'desk-accessories'),
    badge: 'Sale',
    isFeatured: false,
    stock: 32,
    stockStatus: 'In stock',
    variants: [
      { id: 'oak-silver', label: 'Finish', value: 'Oak / Silver', inStock: true },
      { id: 'walnut-black', label: 'Finish', value: 'Walnut / Black', inStock: true },
    ],
    specs: [
      { label: 'Width', value: '42 in workstation shelf' },
      { label: 'Material', value: 'Wood veneer and aluminum' },
      { label: 'Storage', value: 'Hidden accessory tray' },
      { label: 'Load', value: 'Supports up to 70 lb' },
    ],
    relatedProductIds: ['p-018', 'p-037', 'p-019'],
  },
  {
    id: 'p-039',
    slug: 'voltstack-desktop-hub',
    name: 'VoltStack Desktop Hub',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A premium desktop charging hub with display output, fast power, and front ports.',
    longDescription:
      'VoltStack Desktop Hub is built for creator and workstation gear that needs reliable power plus clean connectivity. It sits neatly under a monitor shelf, powers a laptop, drives a display, and keeps fast ports within reach.',
    price: 229,
    rating: 4.7,
    reviewCount: 156,
    imageUrl: productPhoto('p-039'),
    gallery: productGallery('p-039', 'charging-accessories'),
    badge: 'New',
    isFeatured: false,
    stock: 20,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: true },
      { id: 'silver', label: 'Finish', value: 'Silver', inStock: true },
    ],
    specs: [
      { label: 'Power', value: '160W shared desktop supply' },
      { label: 'Ports', value: '6 USB-C, HDMI, Ethernet, SD' },
      { label: 'Display', value: 'Single 8K or dual 4K output' },
      { label: 'Mount', value: 'Desk and shelf mounting plate' },
    ],
    relatedProductIds: ['p-019', 'p-040', 'p-022'],
  },
  {
    id: 'p-040',
    slug: 'fluxline-wireless-tray',
    name: 'FluxLine Wireless Tray',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A leather-lined wireless charging tray for phone, earbuds, watch, and cables.',
    longDescription:
      'FluxLine Wireless Tray turns daily charging into a clean desktop ritual. It aligns phone, earbuds, and watch charging in one premium tray, with a rear USB-C output and a soft-lined surface for small everyday items.',
    price: 179,
    originalPrice: 209,
    rating: 4.6,
    reviewCount: 129,
    imageUrl: productPhoto('p-040'),
    gallery: productGallery('p-040', 'charging-accessories'),
    badge: 'Bestseller',
    isFeatured: false,
    stock: 34,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-leather', label: 'Finish', value: 'Graphite leather', inStock: true },
      { id: 'stone-leather', label: 'Finish', value: 'Stone leather', inStock: true },
    ],
    specs: [
      { label: 'Charging', value: '3-zone wireless charging' },
      { label: 'Output', value: 'Rear 30W USB-C accessory port' },
      { label: 'Surface', value: 'Soft vegan leather tray' },
      { label: 'Safety', value: 'Foreign-object and heat detection' },
    ],
    relatedProductIds: ['p-020', 'p-039', 'p-031'],
  },
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly productsState = signal(products);
  private readonly categoriesState = signal(categories);

  readonly products = this.productsState.asReadonly();
  readonly categories = this.categoriesState.asReadonly();
  readonly featuredProducts = computed(() =>
    this.productsState()
      .filter((product) => product.isFeatured)
      .slice(0, 4),
  );

  getProductBySlug(slug: string): Product | undefined {
    return this.productsState().find((product) => product.slug === slug);
  }

  getProductById(id: string): Product | undefined {
    return this.productsState().find((product) => product.id === id);
  }

  getRelatedProducts(product: Product): Product[] {
    const relatedById = product.relatedProductIds
      .map((id) => this.productsState().find((item) => item.id === id))
      .filter((item): item is Product => Boolean(item));

    const relatedIds = new Set(relatedById.map((item) => item.id));
    const fallbackProducts = this.productsState().filter(
      (item) =>
        item.categoryId === product.categoryId &&
        item.id !== product.id &&
        !relatedIds.has(item.id),
    );

    return [...relatedById, ...fallbackProducts].slice(0, 4);
  }
}
