import { Injectable, computed, signal } from '@angular/core';

import { Product, ProductCategory } from '../models/product.model';

const imageBase = 'https://images.unsplash.com';

const categories: readonly ProductCategory[] = [
  {
    id: 'laptops',
    name: 'Laptops',
    description: 'Thin performance notebooks for design, engineering, and travel.',
    imageUrl: `${imageBase}/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'monitors',
    name: 'Monitors',
    description: 'Color-accurate displays for focused creative and technical work.',
    imageUrl: `${imageBase}/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'headphones',
    name: 'Headphones',
    description: 'Immersive wireless audio with premium materials and long battery life.',
    imageUrl: `${imageBase}/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'keyboards',
    name: 'Keyboards',
    description: 'Low-profile and mechanical boards tuned for precise daily input.',
    imageUrl: `${imageBase}/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'mice',
    name: 'Mice',
    description: 'Ergonomic pointing tools for fast navigation and detailed control.',
    imageUrl: `${imageBase}/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'smartwatches',
    name: 'Smartwatches',
    description: 'Polished wearables for health tracking, calls, and daily planning.',
    imageUrl: `${imageBase}/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'speakers',
    name: 'Speakers',
    description: 'Compact and room-filling speakers with modern wireless connectivity.',
    imageUrl: `${imageBase}/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'webcams',
    name: 'Webcams',
    description: 'Sharp cameras and lighting for executive video calls and streaming.',
    imageUrl: `${imageBase}/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'desk-accessories',
    name: 'Desk Accessories',
    description: 'Finishing pieces that keep premium workstations tidy and intentional.',
    imageUrl: `${imageBase}/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
  {
    id: 'charging-accessories',
    name: 'Charging Accessories',
    description: 'Fast chargers, cables, and docks for modern multi-device setups.',
    imageUrl: `${imageBase}/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80`,
    productCount: 2,
  },
];

const products: readonly Product[] = [
  {
    id: 'p-001',
    slug: 'aureon-luma-14',
    name: 'Aureon Luma 14',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description: 'A 14-inch creator laptop with an aluminum chassis and vivid edge-to-edge display.',
    longDescription:
      'Built for founders, designers, and engineers who move between desk, studio, and client room, the Aureon Luma 14 balances premium materials with serious portable performance. Its high-brightness display, quiet cooling profile, and all-day battery make it a refined daily driver for complex workflows.',
    price: 1899,
    originalPrice: 2099,
    rating: 4.9,
    reviewCount: 328,
    imageUrl: `${imageBase}/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1484788984921-03950022c9ef?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Bestseller',
    isFeatured: true,
    stock: 14,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-1tb', label: 'Finish', value: 'Graphite / 1TB', inStock: true },
      { id: 'silver-1tb', label: 'Finish', value: 'Silver / 1TB', inStock: true },
      { id: 'midnight-2tb', label: 'Finish', value: 'Midnight / 2TB', inStock: false },
    ],
    specs: [
      { label: 'Display', value: '14.2 in 120Hz micro-edge panel' },
      { label: 'Memory', value: '32GB unified high-bandwidth memory' },
      { label: 'Storage', value: '1TB NVMe solid-state drive' },
      { label: 'Battery', value: 'Up to 18 hours' },
    ],
    relatedProductIds: ['p-002', 'p-003', 'p-019'],
  },
  {
    id: 'p-002',
    slug: 'nomadix-pro-16',
    name: 'Nomadix Pro 16',
    categoryId: 'laptops',
    categoryName: 'Laptops',
    description: 'A powerful 16-inch workstation notebook tuned for 3D, code, and video timelines.',
    longDescription:
      'Nomadix Pro 16 is the portable workstation for teams that need desktop-class capability without visual bulk. A wide-gamut display, dedicated creator graphics, and a rigid magnesium frame give it the speed and presence expected from a premium electronics flagship.',
    price: 2499,
    rating: 4.8,
    reviewCount: 214,
    imageUrl: `${imageBase}/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'New',
    isFeatured: true,
    stock: 7,
    stockStatus: 'Low stock',
    variants: [
      { id: 'onyx-2tb', label: 'Configuration', value: 'Onyx / 2TB', inStock: true },
      { id: 'titanium-2tb', label: 'Configuration', value: 'Titanium / 2TB', inStock: true },
    ],
    specs: [
      { label: 'Display', value: '16 in 3.2K color-calibrated panel' },
      { label: 'Graphics', value: 'Creator-class 12GB GPU' },
      { label: 'Memory', value: '64GB performance memory' },
      { label: 'Ports', value: 'Thunderbolt-class USB-C, HDMI, SD reader' },
    ],
    relatedProductIds: ['p-001', 'p-003', 'p-004'],
  },
  {
    id: 'p-003',
    slug: 'prismview-32-studio',
    name: 'PrismView 32 Studio',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A 32-inch 6K studio monitor with a slim metal stand and factory calibration.',
    longDescription:
      'PrismView 32 Studio gives creative teams a spacious, color-accurate canvas with high pixel density and a quiet premium silhouette. It is designed for detail-heavy editing, interface design, and multitasking across demanding desktop workflows.',
    price: 1199,
    originalPrice: 1399,
    rating: 4.9,
    reviewCount: 186,
    imageUrl: `${imageBase}/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: true,
    stock: 19,
    stockStatus: 'In stock',
    variants: [
      { id: 'silver-stand', label: 'Stand', value: 'Silver tilt stand', inStock: true },
      { id: 'black-arm', label: 'Stand', value: 'Black monitor arm', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '6016 x 3384' },
      { label: 'Refresh rate', value: '75Hz' },
      { label: 'Color', value: '98% DCI-P3 coverage' },
      { label: 'Connectivity', value: 'USB-C with 96W charging' },
    ],
    relatedProductIds: ['p-004', 'p-001', 'p-017'],
  },
  {
    id: 'p-004',
    slug: 'arcscale-27-gaming',
    name: 'ArcScale 27 Performance',
    categoryId: 'monitors',
    categoryName: 'Monitors',
    description: 'A 27-inch 4K performance display with fast refresh and ultra-thin bezels.',
    longDescription:
      'ArcScale 27 Performance brings speed and clarity to premium desks, pairing a crisp 4K panel with fluid motion handling for gaming, trading dashboards, and high-density productivity. The minimal stand keeps the workstation clean and adjustable.',
    price: 699,
    rating: 4.7,
    reviewCount: 143,
    imageUrl: `${imageBase}/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Limited',
    isFeatured: false,
    stock: 9,
    stockStatus: 'Low stock',
    variants: [
      { id: 'matte-black', label: 'Finish', value: 'Matte black', inStock: true },
      { id: 'frost-white', label: 'Finish', value: 'Frost white', inStock: true },
    ],
    specs: [
      { label: 'Resolution', value: '3840 x 2160' },
      { label: 'Refresh rate', value: '144Hz' },
      { label: 'Response', value: '1ms gray-to-gray' },
      { label: 'Sync', value: 'Adaptive frame sync' },
    ],
    relatedProductIds: ['p-003', 'p-010', 'p-012'],
  },
  {
    id: 'p-005',
    slug: 'solace-air-headphones',
    name: 'Solace Air Headphones',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description: 'Wireless over-ear headphones with adaptive noise control and soft lambskin pads.',
    longDescription:
      'Solace Air Headphones are tuned for long sessions in open offices, flights, and focused deep work. Adaptive noise control, low-latency wireless audio, and premium cushions create a calm, detailed listening experience without shouting for attention.',
    price: 379,
    originalPrice: 429,
    rating: 4.8,
    reviewCount: 412,
    imageUrl: `${imageBase}/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Bestseller',
    isFeatured: true,
    stock: 31,
    stockStatus: 'In stock',
    variants: [
      { id: 'carbon', label: 'Color', value: 'Carbon', inStock: true },
      { id: 'sandstone', label: 'Color', value: 'Sandstone', inStock: true },
      { id: 'deep-navy', label: 'Color', value: 'Deep navy', inStock: true },
    ],
    specs: [
      { label: 'Battery', value: '46 hours with ANC' },
      { label: 'Drivers', value: '42mm bio-cellulose drivers' },
      { label: 'Charging', value: 'USB-C fast charge' },
      { label: 'Microphones', value: '6 beamforming microphones' },
    ],
    relatedProductIds: ['p-006', 'p-013', 'p-014'],
  },
  {
    id: 'p-006',
    slug: 'aether-buds-pro',
    name: 'Aether Buds Pro',
    categoryId: 'headphones',
    categoryName: 'Headphones',
    description: 'Compact premium earbuds with spatial audio, call isolation, and wireless charging.',
    longDescription:
      'Aether Buds Pro are made for commuters and hybrid teams who want polished sound in a pocketable form. The case supports quick wireless top-ups, while intelligent microphones keep calls crisp in cafes, airports, and shared spaces.',
    price: 229,
    rating: 4.6,
    reviewCount: 267,
    imageUrl: `${imageBase}/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'New',
    isFeatured: false,
    stock: 42,
    stockStatus: 'In stock',
    variants: [
      { id: 'porcelain', label: 'Color', value: 'Porcelain', inStock: true },
      { id: 'graphite', label: 'Color', value: 'Graphite', inStock: true },
    ],
    specs: [
      { label: 'Battery', value: '8 hours, 32 hours with case' },
      { label: 'Water resistance', value: 'IPX5' },
      { label: 'Audio', value: 'Spatial mode with head tracking' },
      { label: 'Case', value: 'Qi wireless charging' },
    ],
    relatedProductIds: ['p-005', 'p-019', 'p-020'],
  },
  {
    id: 'p-007',
    slug: 'keystone-flow-75',
    name: 'Keystone Flow 75',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A hot-swappable 75% mechanical keyboard with gasket mount and premium caps.',
    longDescription:
      'Keystone Flow 75 gives tactile keyboard fans a quieter, more refined board for serious work. The compact layout keeps core keys close, while hot-swap sockets, tuned stabilizers, and sculpted keycaps make it easy to customize without rebuilding the desk.',
    price: 189,
    rating: 4.8,
    reviewCount: 153,
    imageUrl: `${imageBase}/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Limited',
    isFeatured: true,
    stock: 12,
    stockStatus: 'Low stock',
    variants: [
      { id: 'linear-mist', label: 'Switch', value: 'Linear mist', inStock: true },
      { id: 'tactile-ember', label: 'Switch', value: 'Tactile ember', inStock: true },
      { id: 'silent-ash', label: 'Switch', value: 'Silent ash', inStock: false },
    ],
    specs: [
      { label: 'Layout', value: '75% compact with function row' },
      { label: 'Connection', value: 'USB-C, Bluetooth, 2.4GHz' },
      { label: 'Mount', value: 'Double gasket isolation' },
      { label: 'Battery', value: '4000mAh rechargeable' },
    ],
    relatedProductIds: ['p-008', 'p-009', 'p-017'],
  },
  {
    id: 'p-008',
    slug: 'typecraft-slim',
    name: 'TypeCraft Slim',
    categoryId: 'keyboards',
    categoryName: 'Keyboards',
    description: 'A low-profile wireless keyboard with quiet scissor switches and metal top case.',
    longDescription:
      'TypeCraft Slim is built for polished executive desks where quiet typing, clean lines, and instant device switching matter. It pairs with three devices, charges over USB-C, and keeps a precise key feel in a thin aluminum profile.',
    price: 129,
    originalPrice: 159,
    rating: 4.5,
    reviewCount: 98,
    imageUrl: `${imageBase}/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: false,
    stock: 26,
    stockStatus: 'In stock',
    variants: [
      { id: 'space-gray', label: 'Finish', value: 'Space gray', inStock: true },
      { id: 'arctic', label: 'Finish', value: 'Arctic silver', inStock: true },
    ],
    specs: [
      { label: 'Layout', value: 'Full-size low profile' },
      { label: 'Connection', value: 'Bluetooth multi-device' },
      { label: 'Battery', value: 'Up to 4 months' },
      { label: 'Build', value: 'Aluminum top plate' },
    ],
    relatedProductIds: ['p-007', 'p-010', 'p-018'],
  },
  {
    id: 'p-009',
    slug: 'vector-grip-mouse',
    name: 'Vector Grip Mouse',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'An ergonomic wireless mouse with glass-smooth feet and precision tracking.',
    longDescription:
      'Vector Grip Mouse is shaped for long workdays without looking clinical. It combines a high-resolution sensor, quiet clicks, and thoughtful side controls in a premium shell that belongs beside a flagship laptop or workstation display.',
    price: 99,
    rating: 4.7,
    reviewCount: 221,
    imageUrl: `${imageBase}/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Bestseller',
    isFeatured: false,
    stock: 38,
    stockStatus: 'In stock',
    variants: [
      { id: 'right-carbon', label: 'Grip', value: 'Right hand / Carbon', inStock: true },
      { id: 'right-silver', label: 'Grip', value: 'Right hand / Silver', inStock: true },
    ],
    specs: [
      { label: 'Sensor', value: '26K precision optical sensor' },
      { label: 'Buttons', value: '7 programmable controls' },
      { label: 'Battery', value: '90 days per charge' },
      { label: 'Weight', value: '78g' },
    ],
    relatedProductIds: ['p-010', 'p-007', 'p-017'],
  },
  {
    id: 'p-010',
    slug: 'nimbus-track-mouse',
    name: 'Nimbus Track Mouse',
    categoryId: 'mice',
    categoryName: 'Mice',
    description: 'A sculpted productivity mouse with magnetic scroll wheel and gesture controls.',
    longDescription:
      'Nimbus Track Mouse is designed for analysts, editors, and builders who move through dense screens all day. Its magnetic wheel shifts between precise and free-spin scrolling, while gesture zones keep navigation fluid across large canvases.',
    price: 119,
    originalPrice: 139,
    rating: 4.6,
    reviewCount: 176,
    imageUrl: `${imageBase}/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: false,
    stock: 23,
    stockStatus: 'In stock',
    variants: [
      { id: 'black', label: 'Color', value: 'Black', inStock: true },
      { id: 'pearl', label: 'Color', value: 'Pearl', inStock: true },
    ],
    specs: [
      { label: 'Scroll', value: 'Magnetic adaptive wheel' },
      { label: 'Connection', value: 'Bluetooth and 2.4GHz receiver' },
      { label: 'Charging', value: 'USB-C quick charge' },
      { label: 'Surface', value: 'Tracks on glass' },
    ],
    relatedProductIds: ['p-009', 'p-008', 'p-004'],
  },
  {
    id: 'p-011',
    slug: 'tempo-watch-slate',
    name: 'Tempo Watch Slate',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description: 'A refined smartwatch with stainless casing, health sensors, and always-on display.',
    longDescription:
      'Tempo Watch Slate blends daily wellness tracking with a clean dress-watch profile. It handles calls, calendar alerts, workouts, and recovery trends while keeping the materials, strap options, and interface firmly premium.',
    price: 449,
    rating: 4.7,
    reviewCount: 244,
    imageUrl: `${imageBase}/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'New',
    isFeatured: true,
    stock: 17,
    stockStatus: 'In stock',
    variants: [
      { id: 'slate-42', label: 'Case', value: 'Slate steel / 42mm', inStock: true },
      { id: 'champagne-42', label: 'Case', value: 'Champagne steel / 42mm', inStock: true },
    ],
    specs: [
      { label: 'Display', value: 'Always-on AMOLED' },
      { label: 'Sensors', value: 'ECG, oxygen, skin temperature' },
      { label: 'Battery', value: 'Up to 5 days' },
      { label: 'Water rating', value: '5 ATM' },
    ],
    relatedProductIds: ['p-012', 'p-006', 'p-020'],
  },
  {
    id: 'p-012',
    slug: 'pulseband-ultra',
    name: 'PulseBand Ultra',
    categoryId: 'smartwatches',
    categoryName: 'Smartwatches',
    description: 'A rugged titanium fitness watch with dual-frequency GPS and sapphire glass.',
    longDescription:
      'PulseBand Ultra is made for serious training without sacrificing a premium interface. Dual-frequency GPS, sapphire glass, and a high-contrast display support long outdoor sessions, while recovery metrics keep the experience useful at the desk too.',
    price: 599,
    rating: 4.8,
    reviewCount: 189,
    imageUrl: `${imageBase}/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Limited',
    isFeatured: false,
    stock: 5,
    stockStatus: 'Low stock',
    variants: [
      { id: 'titanium-black', label: 'Band', value: 'Titanium / Black trail', inStock: true },
      { id: 'titanium-orange', label: 'Band', value: 'Titanium / Signal orange', inStock: true },
    ],
    specs: [
      { label: 'Case', value: 'Titanium with sapphire crystal' },
      { label: 'GPS', value: 'Dual-frequency positioning' },
      { label: 'Battery', value: 'Up to 12 days' },
      { label: 'Training', value: 'Recovery, routes, intervals' },
    ],
    relatedProductIds: ['p-011', 'p-004', 'p-013'],
  },
  {
    id: 'p-013',
    slug: 'halo-room-speaker',
    name: 'Halo Room Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A compact room speaker with rich stereo pairing and fabric-wrapped acoustics.',
    longDescription:
      'Halo Room Speaker fills offices, kitchens, and studio corners with warm, balanced sound from a compact enclosure. It supports multi-room playback, voice-safe privacy controls, and stereo pairing for a more expansive premium listening setup.',
    price: 249,
    rating: 4.6,
    reviewCount: 138,
    imageUrl: `${imageBase}/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Bestseller',
    isFeatured: false,
    stock: 28,
    stockStatus: 'In stock',
    variants: [
      { id: 'charcoal', label: 'Color', value: 'Charcoal weave', inStock: true },
      { id: 'linen', label: 'Color', value: 'Linen weave', inStock: true },
    ],
    specs: [
      { label: 'Audio', value: '360-degree room tuning' },
      { label: 'Connection', value: 'Wi-Fi, Bluetooth, line-in' },
      { label: 'Pairing', value: 'Stereo and multi-room' },
      { label: 'Controls', value: 'Touch top panel' },
    ],
    relatedProductIds: ['p-014', 'p-005', 'p-006'],
  },
  {
    id: 'p-014',
    slug: 'canto-mini-speaker',
    name: 'Canto Mini Speaker',
    categoryId: 'speakers',
    categoryName: 'Speakers',
    description: 'A travel-ready Bluetooth speaker with anodized shell and bold sound.',
    longDescription:
      'Canto Mini Speaker is the polished portable speaker for hotel rooms, patios, and compact desks. Its anodized shell, water resistance, and surprisingly deep driver array make it feel considered instead of disposable.',
    price: 139,
    originalPrice: 169,
    rating: 4.5,
    reviewCount: 104,
    imageUrl: `${imageBase}/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: false,
    stock: 36,
    stockStatus: 'In stock',
    variants: [
      { id: 'ink', label: 'Color', value: 'Ink', inStock: true },
      { id: 'clay', label: 'Color', value: 'Clay', inStock: true },
      { id: 'mist', label: 'Color', value: 'Mist', inStock: false },
    ],
    specs: [
      { label: 'Battery', value: '18 hours playback' },
      { label: 'Rating', value: 'IP67 dust and water resistance' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pairing', value: 'Dual-speaker stereo mode' },
    ],
    relatedProductIds: ['p-013', 'p-005', 'p-020'],
  },
  {
    id: 'p-015',
    slug: 'clarity-cam-4k',
    name: 'ClarityCam 4K',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A 4K webcam with glass optics, smart framing, and built-in privacy shutter.',
    longDescription:
      'ClarityCam 4K upgrades remote presence with crisp detail, balanced exposure, and a camera body that looks appropriate on a premium monitor. Smart framing keeps the shot composed, while the hardware shutter gives quick visual privacy.',
    price: 199,
    rating: 4.7,
    reviewCount: 132,
    imageUrl: `${imageBase}/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'New',
    isFeatured: false,
    stock: 22,
    stockStatus: 'In stock',
    variants: [
      { id: 'monitor-mount', label: 'Mount', value: 'Monitor mount', inStock: true },
      { id: 'tripod-kit', label: 'Mount', value: 'Tripod creator kit', inStock: true },
    ],
    specs: [
      { label: 'Video', value: '4K at 30fps, 1080p at 60fps' },
      { label: 'Lens', value: 'Glass lens with 90-degree FOV' },
      { label: 'Audio', value: 'Dual noise-reducing microphones' },
      { label: 'Privacy', value: 'Integrated shutter' },
    ],
    relatedProductIds: ['p-016', 'p-003', 'p-018'],
  },
  {
    id: 'p-016',
    slug: 'studioframe-hd',
    name: 'StudioFrame HD',
    categoryId: 'webcams',
    categoryName: 'Webcams',
    description: 'A slim 1080p webcam with soft fill light and automatic white balance.',
    longDescription:
      'StudioFrame HD is the clean everyday camera for polished calls without a heavy creator rig. A soft fill light, automatic white balance, and magnetic mount make it simple to look composed from compact workstations.',
    price: 119,
    originalPrice: 149,
    rating: 4.4,
    reviewCount: 87,
    imageUrl: `${imageBase}/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: false,
    stock: 0,
    stockStatus: 'Sold out',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: false },
      { id: 'silver', label: 'Finish', value: 'Silver', inStock: false },
    ],
    specs: [
      { label: 'Video', value: '1080p at 60fps' },
      { label: 'Lighting', value: 'Adjustable soft LED ring' },
      { label: 'Mount', value: 'Magnetic monitor mount' },
      { label: 'Connection', value: 'USB-C' },
    ],
    relatedProductIds: ['p-015', 'p-004', 'p-007'],
  },
  {
    id: 'p-017',
    slug: 'axis-desk-dock',
    name: 'Axis Desk Dock',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A machined aluminum desk dock with cable routing and weighted device channels.',
    longDescription:
      'Axis Desk Dock keeps premium setups intentional by organizing a laptop, tablet, phone, and active cables in one weighted aluminum base. The finish pairs cleanly with high-end displays and helps busy workstations stay presentation-ready.',
    price: 149,
    rating: 4.6,
    reviewCount: 119,
    imageUrl: `${imageBase}/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Limited',
    isFeatured: false,
    stock: 16,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite', label: 'Finish', value: 'Graphite', inStock: true },
      { id: 'natural', label: 'Finish', value: 'Natural aluminum', inStock: true },
    ],
    specs: [
      { label: 'Material', value: 'CNC aluminum with silicone rails' },
      { label: 'Capacity', value: 'Laptop, tablet, phone, cables' },
      { label: 'Weight', value: '2.4 lb weighted base' },
      { label: 'Cable routing', value: 'Four rear channels' },
    ],
    relatedProductIds: ['p-018', 'p-019', 'p-003'],
  },
  {
    id: 'p-018',
    slug: 'focuspad-pro-mat',
    name: 'FocusPad Pro Mat',
    categoryId: 'desk-accessories',
    categoryName: 'Desk Accessories',
    description: 'A premium desk mat with vegan leather surface and hidden magnetic cable guides.',
    longDescription:
      'FocusPad Pro Mat gives keyboards, mice, and devices a consistent working surface with a refined executive look. Hidden magnetic cable guides and stitched edges make the desk feel finished while staying durable enough for daily use.',
    price: 89,
    rating: 4.5,
    reviewCount: 203,
    imageUrl: `${imageBase}/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Bestseller',
    isFeatured: false,
    stock: 44,
    stockStatus: 'In stock',
    variants: [
      { id: 'stone', label: 'Color', value: 'Stone', inStock: true },
      { id: 'graphite', label: 'Color', value: 'Graphite', inStock: true },
      { id: 'walnut', label: 'Color', value: 'Walnut', inStock: true },
    ],
    specs: [
      { label: 'Size', value: '31.5 x 15.7 in' },
      { label: 'Surface', value: 'Water-resistant vegan leather' },
      { label: 'Base', value: 'Micro-suction non-slip backing' },
      { label: 'Included', value: '2 magnetic cable guides' },
    ],
    relatedProductIds: ['p-017', 'p-008', 'p-009'],
  },
  {
    id: 'p-019',
    slug: 'voltstack-140w-gan',
    name: 'VoltStack 140W GaN',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A compact 140W GaN charger with three USB-C ports and intelligent power sharing.',
    longDescription:
      'VoltStack 140W GaN replaces a bag full of chargers with a single premium brick for laptops, tablets, phones, and headphones. Intelligent power sharing routes wattage where it is needed and keeps the housing compact for travel.',
    price: 119,
    originalPrice: 139,
    rating: 4.8,
    reviewCount: 302,
    imageUrl: `${imageBase}/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'Sale',
    isFeatured: true,
    stock: 52,
    stockStatus: 'In stock',
    variants: [
      { id: 'us-plug', label: 'Plug', value: 'US folding plug', inStock: true },
      { id: 'travel-kit', label: 'Plug', value: 'Global travel kit', inStock: true },
    ],
    specs: [
      { label: 'Output', value: '140W max shared' },
      { label: 'Ports', value: '3 USB-C, 1 USB-A' },
      { label: 'Technology', value: 'GaN power architecture' },
      { label: 'Safety', value: 'Thermal and surge protection' },
    ],
    relatedProductIds: ['p-020', 'p-001', 'p-017'],
  },
  {
    id: 'p-020',
    slug: 'fluxline-magnetic-cable-kit',
    name: 'FluxLine Magnetic Cable Kit',
    categoryId: 'charging-accessories',
    categoryName: 'Charging Accessories',
    description: 'A braided USB-C cable kit with magnetic desk anchors and premium metal tips.',
    longDescription:
      'FluxLine Magnetic Cable Kit keeps charging points exactly where you expect them. Braided high-output cables, magnetic anchors, and color-coded metal tips make the kit practical for desks, travel pouches, and bedside stations.',
    price: 59,
    rating: 4.6,
    reviewCount: 158,
    imageUrl: `${imageBase}/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=900&q=80`,
    gallery: [
      `${imageBase}/photo-1601524909162-ae8725290836?auto=format&fit=crop&w=1200&q=80`,
      `${imageBase}/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80`,
    ],
    badge: 'New',
    isFeatured: false,
    stock: 67,
    stockStatus: 'In stock',
    variants: [
      { id: 'graphite-kit', label: 'Color', value: 'Graphite kit', inStock: true },
      { id: 'silver-kit', label: 'Color', value: 'Silver kit', inStock: true },
    ],
    specs: [
      { label: 'Cables', value: '3 braided USB-C cables' },
      { label: 'Power', value: 'Up to 100W charging' },
      { label: 'Data', value: '10Gbps transfer support' },
      { label: 'Included', value: '4 magnetic cable anchors' },
    ],
    relatedProductIds: ['p-019', 'p-006', 'p-014'],
  },
];

@Injectable({ providedIn: 'root' })
export class ProductService {
  private readonly productsState = signal(products);
  private readonly categoriesState = signal(categories);

  readonly products = this.productsState.asReadonly();
  readonly categories = this.categoriesState.asReadonly();
  readonly featuredProducts = computed(() =>
    this.productsState()
      .filter((product) => product.isFeatured)
      .slice(0, 4),
  );

  getProductBySlug(slug: string): Product | undefined {
    return this.productsState().find((product) => product.slug === slug);
  }

  getRelatedProducts(product: Product): Product[] {
    const relatedById = product.relatedProductIds
      .map((id) => this.productsState().find((item) => item.id === id))
      .filter((item): item is Product => Boolean(item));

    if (relatedById.length > 0) {
      return relatedById.slice(0, 3);
    }

    return this.productsState()
      .filter((item) => item.categoryId === product.categoryId && item.id !== product.id)
      .slice(0, 3);
  }
}
